# Generated by Django 4.1.4 on 2023-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='Image',
        ),
    ]
