# Generated by Django 4.1.4 on 2023-01-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_rename_image_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Image',
        ),
    ]
