# Generated by Django 4.1.3 on 2023-01-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_rename_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
